# Generated by Django 5.2.12 on 2026-04-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
