# Generated by Django 5.2.12 on 2026-04-02 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTracking',
            fields=[
                ('page', models.CharField(max_length=20)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='CC', max_length=5)),
                ('kind', models.CharField(default='OP', max_length=2)),
                ('steps', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in_progress', 'IN_PROGRESS'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.usuario')),
            ],
            options={
                'db_table': 'page_tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
