# Generated by Django 5.2.12 on 2026-04-29 17:12

import django.core.validators
import scrapying.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapying', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagetracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Page Tracking', 'verbose_name_plural': 'Page Trackings'},
        ),
        migrations.RemoveField(
            model_name='pagetracking',
            name='user',
        ),
        migrations.AddField(
            model_name='pagetracking',
            name='metadata',
            field=scrapying.models.SafeJSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pagetracking',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagetracking',
            name='kind',
            field=models.CharField(choices=[('OP', 'OP'), ('OT', 'Other')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='pagetracking',
            name='page',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pagetracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagetracking',
            name='steps',
            field=scrapying.models.SafeJSONField(),
        ),
        migrations.AlterField(
            model_name='pagetracking',
            name='type',
            field=models.CharField(choices=[('CC', 'CC'), ('OT', 'Other')], default='CC', max_length=5),
        ),
        migrations.AddIndex(
            model_name='pagetracking',
            index=models.Index(fields=['page'], name='page_tracki_page_7ca448_idx'),
        ),
        migrations.AddIndex(
            model_name='pagetracking',
            index=models.Index(fields=['status'], name='page_tracki_status_b62635_idx'),
        ),
        migrations.AddIndex(
            model_name='pagetracking',
            index=models.Index(fields=['user_id'], name='page_tracki_user_id_df2844_idx'),
        ),
        migrations.AddIndex(
            model_name='pagetracking',
            index=models.Index(fields=['created_at'], name='page_tracki_created_4a9442_idx'),
        ),
    ]
