# Generated by Django 5.2.12 on 2026-04-02 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegConsulta',
            fields=[
                ('consulta_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('en_proceso', 'EN PROCESO'), ('completada', 'COMPLETADA'), ('cancelada', 'CANCELADA')], default='pendiente', max_length=50)),
                ('prioridad', models.IntegerField(default=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.usuario')),
            ],
            options={
                'verbose_name_plural': 'Reg Consultas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRegConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('reg_encontrados', models.PositiveIntegerField(default=0)),
                ('tiempo_busqueda_ms', models.IntegerField(blank=True, null=True)),
                ('creado_al', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='consultas.regconsulta')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='consultas/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamaño_kb', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hash_md5', models.CharField(blank=True, max_length=32, null=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.usuario')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='consultas.regconsulta')),
            ],
        ),
    ]
