# Generated by Django 5.2.12 on 2026-04-08 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleregconsulta',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='regconsulta',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='regconsulta',
            name='usuario',
        ),
        migrations.CreateModel(
            name='ValidacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_exitosos', models.IntegerField(default=0)),
                ('registros_fallidos', models.IntegerField(default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='validaciones/archivos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_archivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validación de Archivo',
                'verbose_name_plural': 'Validaciones de Archivos',
                'db_table': 'validaciones_archivo',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
        migrations.CreateModel(
            name='RegistroValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte')], max_length=2)),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('mensaje_respuesta', models.TextField(blank=True, null=True)),
                ('respuesta_json', models.JSONField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('validacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='consultas.validacionarchivo')),
            ],
            options={
                'verbose_name': 'Registro de Validación',
                'verbose_name_plural': 'Registros de Validaciones',
                'db_table': 'registros_validacion',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
        migrations.DeleteModel(
            name='ArchivoCarga',
        ),
        migrations.DeleteModel(
            name='DetalleRegConsulta',
        ),
        migrations.DeleteModel(
            name='RegConsulta',
        ),
    ]
